version: "3.7"

services:

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: insights
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      PG_HOST: postgres
      PG_USER: postgres
      PG_PASSWORD: supersecret
      PG_DATABASE: insights
    volumes:
      - grafana_lib:/var/lib/grafana
      - grafana_etc:/etc/grafana
      - grafana_log:/var/log/grafana
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - /var/lib/grafana/dashboards/

volumes:
  grafana_lib:
  grafana_etc:
  grafana_log: